AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create the infrastructure for the Ticket App.
Parameters:
  YourName:
    Type: String
  MasterUser:
    Type: String
  MasterPass:
    Type: String
  JwtSecretKey:
    Type: String
Resources:
  SqsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sam-ticket-app/infrastructure/017cfb74aa0a25cd7ee93eb8e2aea7d1.template
      TimeoutInMinutes: 30
      Parameters:
        YourName:
          Ref: YourName
    Metadata:
      SamResourceId: SqsStack
  NetworkSecStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sam-ticket-app/infrastructure/6b234798bddf0c7c10f24b6b1940bbfb.template
      TimeoutInMinutes: 30
      Parameters:
        YourName:
          Ref: YourName
        MasterUser:
          Ref: MasterUser
        MasterPass:
          Ref: MasterPass
        JwtSecretKey:
          Ref: JwtSecretKey
    Metadata:
      SamResourceId: NetworkSecStack
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sam-ticket-app/infrastructure/f567be55ae296b890fb7008353c3be77.template
      TimeoutInMinutes: 30
      Parameters:
        YourName:
          Ref: YourName
    Metadata:
      SamResourceId: DynamoDBStack
  DocumentDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sam-ticket-app/infrastructure/9f31cd114219011bc5c43cba719a7715.template
      TimeoutInMinutes: 30
      Parameters:
        SubnetIds:
          Fn::Join:
          - ','
          - - Fn::GetAtt:
              - NetworkSecStack
              - Outputs.PrivateSubnet1Id
            - Fn::GetAtt:
              - NetworkSecStack
              - Outputs.PrivateSubnet2Id
        SecurityGroupDBId:
          Fn::GetAtt:
          - NetworkSecStack
          - Outputs.SecurityGroupId
        ClusterIdentifier:
          Fn::Sub: docdb-${YourName}-prod
        InstanceIdentifier:
          Fn::Sub: docdb-${YourName}-instance-prod
        SecretArn:
          Fn::GetAtt:
          - NetworkSecStack
          - Outputs.SecretArn
    Metadata:
      SamResourceId: DocumentDBStack
