AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation template to create the serverless model for the Ticket
  App.
Parameters:
  YourName:
    Type: String
  JwtSecret:
    Type: String
Resources:
  TicketAppFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sam-ticket-app/serverless/ab6c964e6914ccf4ccc82f12a996d490.template
      TimeoutInMinutes: 30
      Parameters:
        JwtSecret:
          Ref: JwtSecret
        DynamoTable:
          Fn::ImportValue: MyDynamoDBTableName
        QueueName:
          Fn::ImportValue: TicketQueueName
        SecretName:
          Fn::Sub: Starry-Credentials-${YourName}
        SecretArn:
          Fn::ImportValue: SecretArn
        SecurityGroup:
          Fn::ImportValue: SecurityGroupId
        DocumentDBClusterEndpoint:
          Fn::ImportValue: DocumentDBEndpoint
        SubnetIds:
          Fn::Join:
          - ','
          - - Fn::ImportValue: PrivateSubnet1Id
            - Fn::ImportValue: PrivateSubnet2Id
    Metadata:
      SamResourceId: TicketAppFunction
